### ISSUE TITLE
sqlite3.OperationalError: no such table: users

### ISSUE THREAD

**Issue by jamalnggau1** [Alexsey272/Anon-Plaid#1]
how do i populate YANDEX_API and PAYMENTS. I'm having a hard time filling it out because I'm not a Russian citizen

**Comment by Alexsey272** [comment]
These fields were necessary to connect the payment system via Yoomoney, they are not used in this version, payment is made via the Yoomoney API, you can read about this in the documentation https://yoomoney.ru/docs/wallet or look at the examples on Github - https://github.com/AlekseyKorshuk/yoomoney-api Whether they work in your country, I can't say for sure
--
Отправлено из VK Почта для Android вторник, 23 ноября 2021г., 12:48 +07:00 от Jamal nggau  ***@***.*** :

**Comment by jamalnggau1** [comment]
i found this error. Help me🙏


exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/usr/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('no such table: users')>

 File "/storage/emulated/0/Bot/Anon-Plaid/handlers/users_handlers/users_handlers.py", line 19, in start
    if not db.user_exists(message.from_user.id):
  File "/storage/emulated/0/Bot/Anon-Plaid/utils/db_api/database.py", line 13, in user_exists
    result = self.cursor.execute('SELECT * FROM `users` WHERE `telegram_id` = ?', (user_id,)).fetchall()
sqlite3.OperationalError: no such table: users

**Comment by jamalnggau1** [comment]
how to solve this?
Is this a bug?

Anon-Plaid/utils/db_api/database.py", line 13, in user_exists
result = self.cursor.execute('SELECT * FROM users WHERE telegram_id = ?',
(user_id,)).fetchall()
sqlite3.OperationalError: no such table: users

Pada tanggal Sel, 23 Nov 2021 14.31, Алексей ***@***.***>
menulis:

**Comment by Alexsey272** [comment]
There is no database file, so the program throws exceptions, tomorrow I will add a database to the repository
--
Отправлено из VK Почта для Android вторник, 23 ноября 2021г., 17:53 +07:00 от Jamal nggau  ***@***.*** :

**Comment by jamalnggau1** [comment]
i think i should fetch the database from here https://github.com/RenatYakublevich/AnonymChat but after i tried it didn't work.

**Comment by Alexsey272** [comment]
Tomorrow I will add the database to the repository, today, unfortunately, there are no opportunities.
--
Отправлено из VK Почта для Android вторник, 23 ноября 2021г., 18:33 +07:00 от Jamal nggau  ***@***.*** :

**Comment by jamalnggau1** [comment]
a little suggestion for the main menu display. there should be a registration menu like the one here
https://github.com/Tokimaro/Anonim_tg_bot
And without compromising other features
but this project has been abandoned for a long time, it's a shame☹️

**Comment by jamalnggau1** [comment]
> Besok saya akan menambahkan database ke repositori, hari ini, sayangnya, tidak ada peluang. - Dikirim dari VK Mail untuk Android Selasa, 23 November 2021, 18:33 +07: 00 dari Jamal nggau ***@***.***:
> […](#)

thanks very much. good luck to you, there are still many questions i want to ask but i think you are very busy. I will ask again after I successfully run the bot

**Comment by Alexsey272** [comment]
Now I am translating the chat, including adding English, so far not everything has been translated, I will finish with the translation and take care of your offer, and add the registration menu, I understand that registration should be with the possibility of skipping
--
Отправлено из VK Почта для Android вторник, 23 ноября 2021г., 18:47 +07:00 от Jamal nggau  ***@***.*** :

**Comment by Alexsey272** [comment]
Tomorrow I will add a database and unsubscribe to you, I will be glad to answer your questions and hear new suggestions for improving the project
--
Отправлено из VK Почта для Android вторник, 23 ноября 2021г., 18:52 +07:00 от Jamal nggau  ***@***.*** :

**Comment by jamalnggau1** [comment]
If you don't mind and the database has been added, I will contribute to translating this bot🙏

I hope you don't miss this feature https://github.com/Tokimaro/Anonim_tg_bot/blob/638f6b7470cbf181e44c3d193d13d6219ce9646f/main.py#L148

**Comment by Alexsey272** [comment]
I will add a menu with registration, and I can do the translation myself, there is not much left, but I will be grateful if you help with testing it, and point out any errors in the translation, or places where the translation was skipped
--
Отправлено из VK Почта для Android вторник, 23 ноября 2021г., 19:16 +07:00 от Jamal nggau  ***@***.*** :

**Comment by jamalnggau1** [comment]
> Saya akan menambahkan menu dengan pendaftaran, dan saya dapat melakukan terjemahan sendiri, tidak banyak yang tersisa, tetapi saya akan berterima kasih jika Anda membantu mengujinya, dan menunjukkan kesalahan dalam terjemahan, atau tempat-tempat di mana terjemahan dilewati -- авлено VK очта Android орник, 23 оября 2021г., 19:16 +07:00 от Jamal nggau ***@***.*** :
> […](#)
> Jika Anda tidak keberatan dan database telah ditambahkan, saya akan berkontribusi untuk menerjemahkan bot ini🙏 I hope you don't miss this feature https://github.com/Tokimaro/Anonim_tg_bot/blob/638f6b7470cbf181e44c3d193d13d6219ce9646f/main.py#L148 — You are receiving this because you commented. Reply to this email directly, view it on GitHub , or unsubscribe .

I am very glad to hear it. I've seen which features I'm going to test😁
.allmsg
.message
.Account
.ban
.unban
because I think that feature is really awesome,
Hopefully it can run normally without errors. I can't wait for tomorrow😁

**Comment by jamalnggau1** [comment]
I want to ask one more question. provide detailed examples to fill in BOT_OWNER, SUBSCRIBE, PAYMENTS, YANDEX_API.
You can create an .env.example file to provide an example.
if busy can answer tomorrow😁

**Comment by Alexsey272** [comment]
the allmsg function, to be honest, has not been tested at all, the rest seems to work, but in connection with the translation, something may break 😅
--
Отправлено из VK Почта для Android вторник, 23 ноября 2021г., 19:50 +07:00 от Jamal nggau  ***@***.*** :

**Comment by Alexsey272** [comment]
tomorrow I will add env template to make it clearer 😉
--
Отправлено из VK Почта для Android вторник, 23 ноября 2021г., 19:52 +07:00 от Jamal nggau  ***@***.*** :

**Comment by jamalnggau1** [comment]
> fungsi allmsg, sejujurnya, belum diuji sama sekali, sisanya tampaknya berfungsi, tetapi sehubungan dengan terjemahan, ada sesuatu yang mungkin rusak 😅 -- авлено VK очта Android орник, 23 оября 2021г., 19:50 +07:00 от Jamal nggau ***@***.*** :
> […](#)
> >Saya akan menambahkan menu dengan pendaftaran, dan saya dapat melakukan terjemahan sendiri, tidak banyak yang tersisa, tetapi saya akan berterima kasih jika Anda membantu mengujinya, dan menunjukkan kesalahan dalam terjemahan, atau tempat-tempat di mana terjemahan dilewati -- авлено VK очта Android орник, 23 оября 2021г., 19:16 +07:00 от Jamal nggau @ .*** : >… >Jika Anda tidak keberatan dan database telah ditambahkan, saya akan berkontribusi untuk menerjemahkan bot ini🙏 I hope you don't miss this feature https://github.com/Tokimaro/Anonim_tg_bot/blob/638f6b7470cbf181e44c3d193d13d6219ce9646f/main.py#L148 — You are receiving this because you commented. Reply to this email directly, view it on GitHub , or unsubscribe . I am very glad to hear it. I've seen which features I'm going to test😁 .allmsg .message .Account .tire .unban because I think that feature is really awesome, Hopefully it can run normally without errors. I can't wait for tomorrow — You are receiving this because you commented. Reply to this email directly, view it on GitHub , or unsubscribe .

I can't wait to test it😁

**Comment by jamalnggau1** [comment]
> besok saya tambahin env template biar lebih jelas 😉 -- авлено VK очта Android орник, 23 оября 2021г., 19:52 +07:00 от Jamal nggau ***@***.*** :
> […](#)
> Saya ingin mengajukan satu pertanyaan lagi. berikan contoh detail untuk mengisi BOT_OWNER, SUBSCRIBE, PAYMENTS, YANDEX_API. Anda dapat membuat file .env.example untuk memberikan contoh. kalo sibuk bisa jawab besok😁 — Anda menerima ini karena Anda berkomentar. Balas email ini secara langsung, lihat di GitHub , atau berhenti berlangganan .

ok thank you very much☺

**Comment by jamalnggau1** [comment]
I'm really looking forward to the good news☺

Pada tanggal Sel, 23 Nov 2021 20.57, Алексей ***@***.***>
menulis:

**Comment by jamalnggau1** [comment]
i still find the same error☹😭


Anon-Plaid/utils/db_api/database.py", line 13, in user_exists result = self.cursor.execute('SELECT * FROM `users` WHERE `telegram_id` = ?', (user_id,)).fetchall() sqlite3.OperationalError: no such table: users


should I replace the name "example.db" with "db_dumb1.db".? and you also forgot to add the logs folder.but that was resolved.
but i have problem with db.
 what do I have to do?☹😭

**Comment by Alexsey272** [comment]
Rename example.db on db_dumb1.db
--
Отправлено из VK Почта для Android четверг, 25 ноября 2021г., 13:40 +07:00 от Jamal nggau  ***@***.*** :

**Comment by jamalnggau1** [comment]
I found this error code

Anon-Plaid/utils/db_api/database.py", line 13, in user_exists result = self.cursor.execute('SELECT * FROM `users` WHERE `telegram_id` = ?', (user_id,)).fetchall() sqlite3.DatabaseError: file is not a database

**Comment by Alexsey272** [comment]
try it with a new database that I have now added
--
Отправлено из VK Почта для Android четверг, 25 ноября 2021г., 13:57 +07:00 от Jamal nggau  ***@***.*** :

**Comment by jamalnggau1** [comment]
I will try it

**Comment by jamalnggau1** [comment]
it works. I think you have finished translating this bot.😁 if I find a mistake I will ask again😁

**Comment by Alexsey272** [comment]
This is a version without translation, since the translation is not finished yet, and has many bugs
--
Отправлено из VK Почта для Android четверг, 25 ноября 2021г., 14:33 +07:00 от Jamal nggau  ***@***.*** :

**Comment by jamalnggau1** [comment]
2021-11-25 15:45:16,053 - ERROR -Chat not found
Traceback (most recent call last):
  File "/storage/emulated/0/botenak/Anon-Plaid/utils/notify.py", line 9, in on_startup_notify
    await dp.bot.send_message(admin, datetime.datetime.today().strftime("%d.%m.%Y %H:%M:%S") + "\n[INFO] The bot is running")



I found this error code while searching for a partner

**Comment by Alexsey272** [comment]
add administrators to the database and env
--
Отправлено из VK Почта для Android четверг, 25 ноября 2021г., 14:55 +07:00 от Jamal nggau  ***@***.*** :

**Comment by jamalnggau1** [comment]
i have added administrator to env. but I haven't added to Database, I don't know how to do that

**Comment by jamalnggau1** [comment]
if i use admin account i can do friend search. but if i use non admin i can't do friend search

bot works very well if i use admin account

**Comment by Alexsey272** [comment]
via sqlite studio or sqlite browser
--
Отправлено из VK Почта для Android четверг, 25 ноября 2021г., 15:06 +07:00 от Jamal nggau  ***@***.*** :

**Comment by jamalnggau1** [comment]
> melalui sqlite studio atau browser sqlite - Dikirim dari VK Mail untuk Android Kamis 25 November 2021 15:06 +07:00 dari Jamal nggau ***@***.***:
> […](#)
> saya telah menambahkan administrator ke env. tapi saya belum menambahkan ke Database, saya tidak tahu bagaimana melakukannya — Anda menerima ini karena Anda mengubah status buka/tutup. Balas email ini secara langsung, lihat di GitHub , atau berhenti berlangganan .

I will try it

**Comment by Alexsey272** [comment]
you can, the program just needs to know who to notify about the correct launch, and who to grant access to the admin panel
--
Отправлено из VK Почта для Android четверг, 25 ноября 2021г., 15:08 +07:00 от Jamal nggau  ***@***.*** :

**Comment by jamalnggau1** [comment]
sorry sir i only use android. do i still have hope?☹️
![Screenshot_2021-11-25-16-24-26-411_com tomminosoftware sqliteeditor](https://user-images.githubusercontent.com/44499007/143405525-a5763364-0919-44d7-ba87-1b2b93abd3c4.jpg)

**Comment by Alexsey272** [comment]
unfortunately, you can only work with the database on a computer
--
Отправлено из VK Почта для Android четверг, 25 ноября 2021г., 15:25 +07:00 от Jamal nggau  ***@***.*** :

**Comment by jamalnggau1** [comment]
thank you. if i have got the computer i will ask again😁
